### ISSUE TITLE
关于模型的用法和数据集

### ISSUE THREAD

**Issue by LoveYstT** [RDXiaoLu/SCoralDet#1]
1. 项目中有yolov10n_backbone.yaml和yolov10n_lightneck.yaml两个模型，在train.py里model = YOLO('  ')使用应该哪个呀？
2. SCoralDet数据集一共有多少个nc？分别都是什么？有的class_id是-1，这是为什么呀？

**Comment by RDXiaoLu** [comment]
1. The yolov10n_backbone.yaml corresponds to improvements in the MPFB, while the lightneck.yaml corresponds to improvements in the neck. You can combine them together as needed.

2. The SCoralDet dataset contains 6 types of coral, with class_id ranging from 0 to 5. There should not be any class_id with a value of -1.

Thank you for your interest in my work.

**Comment by LoveYstT** [comment]
1. 可以详细说一下怎么结合吗，我是初学实在不太会，麻烦了
2. 比如这第4个的class_id就是-1
![image](https://github.com/user-attachments/assets/7cac714f-6a73-4ff1-9424-b7e4f92499ae)

**Comment by RDXiaoLu** [comment]
1. I’ve combined them for you, and you can check the file at lib/cfg/models/v10/yolov10n_combine.yaml.

2. Is this the annotation file generated by running coco2yolo.py? There might have been an error in the earlier steps. I recommend carefully checking whether a -1 appeared during the previous steps.

**Comment by LoveYstT** [comment]
1. 非常感谢
2. 好的，我再检查一下前面的步骤

**Comment by LoveYstT** [comment]
![Uploading image.png…]()
这个Bottleneck和C2f是分别属于哪个库呀

**Comment by LoveYstT** [comment]
这个Bottleneck和C2f是分别属于哪个库呀
![image](https://github.com/user-attachments/assets/13168c6e-182c-498c-b24e-b77b9eb36127)

**Comment by LoveYstT** [comment]
task.py里的parse_model函数是怎么修改的呀

**Comment by RDXiaoLu** [comment]
For example:
`
for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
        try:
            if m == 'node_mode':
                m = d[m]
                if len(args) > 0:
                    if args[0] == 'head_channel':
                        args[0] = int(d[args[0]])
            t = m
            m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
        except:
            pass
        for j, a in enumerate(args):
            if isinstance(a, str):
                with contextlib.suppress(ValueError):
                    try:
                        args[j] = locals()[a] if a in locals() else ast.literal_eval(a)
                    except:
                        args[j] = a
        n = n_ = max(round(n * depth), 1) if n > 1 else n  # depth gain
        if m in {
            C2f_MPFB
        }:
        if args[0] == 'head_channel':
                args[0] = d[args[0]]
            c1, c2 = ch[f], args[0]
            if c2 != nc:  # if c2 not equal to number of classes (i.e. for Classify() output)
                c2 = make_divisible(min(c2, max_channels) * width, 8)
            if m is C2fAttn:
                args[1] = make_divisible(min(args[1], max_channels // 2) * width, 8)  # embed channels
                args[2] = int(
                    max(round(min(args[2], max_channels // 2 // 32)) * width, 1) if args[2] > 1 else args[2]
                )  # num heads

            args = [c1, c2, *args[1:]]
            if m in {
                     C2f_MPFB
                     }:
                args.insert(2, n)  # number of repeats
                n = 1
`

**Comment by LoveYstT** [comment]
感谢

**Comment by RDXiaoLu** [comment]
Thank you for bringing this up. I'm closing this issue now as it has been resolved. If you find the project useful, a ⭐ on the repository would be greatly appreciated.

**Comment by LoveYstT** [comment]
好的，作为初学者也谢谢你的帮助

**Comment by LoveYstT** [comment]
在task.py里的parse_model函数有添加VoVGSCSP相关的代码嘛

**Comment by RDXiaoLu** [comment]
Just like adding C2f_MPFB, you only need to:
```
if m in {
            C2f_MPFB, VoVGSCSP 
        }:
```

**Comment by LoveYstT** [comment]
应该加到哪个if里面，你上面发的那段代码有两个
if m in {
                     C2f_MPFB
                     }:

**Comment by RDXiaoLu** [comment]
> 应该加到哪个if里面，你上面发的那段代码有两个 if m in { C2f_MPFB }:

Add it to both.

**Comment by LoveYstT** [comment]
好的，然后GSConv也是这么加对吧

**Comment by RDXiaoLu** [comment]
> 好的，然后GSConv也是这么加对吧

yep

**Comment by LoveYstT** [comment]
Traceback (most recent call last):
  File "E:\yolov11 model\yolo\ultralytics-main\train.py", line 8, in <module>
    model = YOLO(r'E:\yolov11 model\yolo\ultralytics-main\ultralytics\cfg\models\v10\yolov10n_combined.yaml')
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\engine\model.py", line 144, in __init__
    self._new(model, task=task, verbose=verbose)
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\engine\model.py", line 255, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\tasks.py", line 337, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in _forward(torch.zeros(1, ch, s, s))])  # forward
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\tasks.py", line 334, in _forward
    return self.forward(x)["one2many"]
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\tasks.py", line 113, in forward
    return self.predict(x, *args, **kwargs)
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\tasks.py", line 131, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\tasks.py", line 152, in _predict_once
    x = m(x)  # run
  File "C:\Users\84644\.conda\envs\yolo_v10_xin\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\extra_modules\block.py", line 504, in forward
    x1 = self.gsb(self.cv1(x))
  File "C:\Users\84644\.conda\envs\yolo_v10_xin\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\yolov11 model\yolo\ultralytics-main\ultralytics\nn\extra_modules\block.py", line 36, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Users\84644\.conda\envs\yolo_v10_xin\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\84644\.conda\envs\yolo_v10_xin\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\84644\.conda\envs\yolo_v10_xin\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 448, 1, 1], expected input[1, 192, 32, 32] to have 448 channels, but got 192 channels instead
![image](https://github.com/user-attachments/assets/9a94ac46-fc88-4504-b809-5b633096a351)
我在train的时候遇到了这个错误，想请问一下我这个是怎么回事
我查看了堆栈信息，在VoVGSCSP的前向传播的时候出现了这个问题
![1735173710465](https://github.com/user-attachments/assets/7935248b-09cb-43f1-b00f-c68e7a145cee)

**Comment by RDXiaoLu** [comment]
This seems like an issue with a mismatch in the number of channels, which normally shouldn't happen. Perhaps you could leave your contact information, and I'll see if I can help you resolve it.

**Comment by LoveYstT** [comment]
我的邮箱846445995@qq.com
微信15941607395

**Comment by jie-cy** [comment]
> task.py 里的parse_model函数是怎么修改的呀

**Comment by jie-cy** [comment]
作者你好，我在运行 coco2yolo.py 时一直出现这个·问题，试了很多方法都没有把标签格式转换成功，这是为什么呀
![微信图片_20241227103817](https://github.com/user-attachments/assets/f729ebdc-d566-4db0-9712-e0fdbeea85f4)

**Comment by RDXiaoLu** [comment]
> 作者你好，我在运行 coco2yolo.py 时一直出现这个·问题，试了很多方法都没有把标签格式转换成功，这是为什么呀 ![微信图片_20241227103817](https://private-user-images.githubusercontent.com/181575628/398831881-f729ebdc-d566-4db0-9712-e0fdbeea85f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjk1NjUsIm5iZiI6MTczNTI2OTI2NSwicGF0aCI6Ii8xODE1NzU2MjgvMzk4ODMxODgxLWY3MjllYmRjLWQ1NjYtNGRiMC05NzEyLWUwZmRiZWVhODVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMzE0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDg2NGYzOWFmMTY1MTRlMjVkNjQxMmI5ZmRhN2ExMDdlMDZjYjFjYmJmOTg4ZTk4YjI2OGZmNzk2Njc2ZmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.19z1hFZtJosp7xsPIkq11cOM2GSooLI7UnLvoVHXvgU)

You failed to open that folder, I guess your programming software requires administrator privileges. 
Thank you for your interest in my work.

**Comment by RDXiaoLu** [comment]
> > task.py 里的parse_model函数是怎么修改的呀
I have answered a similar question above. You should be able to find the answer you're looking for there. Thank you.

**Comment by jie-cy** [comment]
> > 作者你好，我在运行 coco2yolo.py 时一直出现这个·问题，试了很多方法都没有把标签格式转换成功，这是为什么呀 ![微信图片_20241227103817](https://private-user-images.githubusercontent.com/181575628/398831881-f729ebdc-d566-4db0-9712-e0fdbeea85f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjk1NjUsIm5iZiI6MTczNTI2OTI2NSwicGF0aCI6Ii8xODE1NzU2MjgvMzk4ODMxODgxLWY3MjllYmRjLWQ1NjYtNGRiMC05NzEyLWUwZmRiZWVhODVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMzE0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDg2NGYzOWFmMTY1MTRlMjVkNjQxMmI5ZmRhN2ExMDdlMDZjYjFjYmJmOTg4ZTk4YjI2OGZmNzk2Njc2ZmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.19z1hFZtJosp7xsPIkq11cOM2GSooLI7UnLvoVHXvgU)
> 
> You failed to open that folder, I guess your programming software requires administrator privileges. Thank you for your interest in my work.

请问你有yolo格式的标签吗

**Comment by RDXiaoLu** [comment]
> > > 作者你好，我在运行 coco2yolo.py 时一直出现这个·问题，试了很多方法都没有把标签格式转换成功，这是为什么呀 ![微信图片_20241227103817](https://private-user-images.githubusercontent.com/181575628/398831881-f729ebdc-d566-4db0-9712-e0fdbeea85f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjk1NjUsIm5iZiI6MTczNTI2OTI2NSwicGF0aCI6Ii8xODE1NzU2MjgvMzk4ODMxODgxLWY3MjllYmRjLWQ1NjYtNGRiMC05NzEyLWUwZmRiZWVhODVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMzE0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDg2NGYzOWFmMTY1MTRlMjVkNjQxMmI5ZmRhN2ExMDdlMDZjYjFjYmJmOTg4ZTk4YjI2OGZmNzk2Njc2ZmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.19z1hFZtJosp7xsPIkq11cOM2GSooLI7UnLvoVHXvgU)
> > 
> > 
> > You failed to open that folder, I guess your programming software requires administrator privileges. Thank you for your interest in my work.
> 
> 请问你有yolo格式的标签吗
Apologies, I am unable to provide you with YOLO format labels at the moment due to certain reasons. Please follow the dataset preparation instructions in the Readme.md step by step to generate the YOLO format.  

Please follow the instructions after downloading the dataset: first, execute [3. Processing the Dataset](https://github.com/RDXiaoLu/SCoralDet/tree/main?tab=readme-ov-file#3-training-the-model) , and then proceed to [4. Converting COCO to YOLO Format](https://github.com/RDXiaoLu/SCoralDet/tree/main?tab=readme-ov-file#4-converting-coco-to-yolo-format) . This will allow you to obtain the YOLO-format dataset. If you still encounter difficulties, please feel free to contact me again, and I will generate the YOLO-format dataset based on the raw data and provide it to you.

**Comment by jie-cy** [comment]
> > > > 作者你好，我在运行 coco2yolo.py 时一直出现这个·问题，试了很多方法都没有把标签格式转换成功，这是为什么呀![微信图片_20241227103817](https://private-user-images.githubusercontent.com/181575628/398831881-f729ebdc-d566-4db0-9712-e0fdbeea85f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjk1NjUsIm5iZiI6MTczNTI2OTI2NSwicGF0aCI6Ii8xODE1NzU2MjgvMzk4ODMxODgxLWY3MjllYmRjLWQ1NjYtNGRiMC05NzEyLWUwZmRiZWVhODVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMzE0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDg2NGYzOWFmMTY1MTRlMjVkNjQxMmI5ZmRhN2ExMDdlMDZjYjFjYmJmOTg4ZTk4YjI2OGZmNzk2Njc2ZmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.19z1hFZtJosp7xsPIkq11cOM2GSooLI7UnLvoVHXvgU)
> > > 
> > > 
> > > 您未能打开该文件夹，我猜您的编程软件需要管理员权限。感谢您对我的工作感兴趣。
> > 
> > 
> > 请问你有yolo格式的标签吗
> 
> 很抱歉，由于某些原因，我目前无法为您提供 YOLO 格式标签。请按照 Readme.md 中的数据集准备说明逐步生成 YOLO 格式。
> 
> 下载数据集后，请按照说明进行操作：首先，执行 [3。处理 数据集](https://github.com/RDXiaoLu/SCoralDet/tree/main?tab=readme-ov-file#3-training-the-model) ，然后继续 [4.将 COCO 转换为 YOLO 格式](https://github.com/RDXiaoLu/SCoralDet/tree/main?tab=readme-ov-file#4-converting-coco-to-yolo-format) .这将允许您获取 YOLO 格式的数据集。如果您仍然遇到困难，请随时再次联系我，我会根据原始数据生成 YOLO 格式的数据集并提供给您。

好的，感谢，我再试试

**Comment by jie-cy** [comment]
导师催的比较紧。麻烦您提供一下yolo格式的数据集




常玉洁193205032044
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RDXiaoLu/SCoralDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月27日(星期五) 中午11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RDXiaoLu/SCoralDet] 关于模型的用法和数据集 (Issue #1)





    
作者你好，我在运行 coco2yolo.py 时一直出现这个·问题，试了很多方法都没有把标签格式转换成功，这是为什么呀 
  
You failed to open that folder, I guess your programming software requires administrator privileges. Thank you for your interest in my work.
  
请问你有yolo格式的标签吗
  
Apologies, I am unable to provide you with YOLO format labels at the moment due to certain reasons. Please follow the dataset preparation instructions in the Readme.md step by step to generate the YOLO format.
 
Please follow the instructions after downloading the dataset: first, execute 3. Processing the Dataset , and then proceed to 4. Converting COCO to YOLO Format . This will allow you to obtain the YOLO-format dataset. If you still encounter difficulties, please feel free to contact me again, and I will generate the YOLO-format dataset based on the raw data and provide it to you.

**Comment by jie-cy** [comment]
![{5F32F8C4-D9E0-4A02-8886-3E51F7AF1253}](https://github.com/user-attachments/assets/c5465bd2-9df1-4cd5-9277-651b91cbd899)

**Comment by RDXiaoLu** [comment]
> ![{5F32F8C4-D9E0-4A02-8886-3E51F7AF1253}](https://private-user-images.githubusercontent.com/181575628/400123032-c5465bd2-9df1-4cd5-9277-651b91cbd899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNDIxNTUsIm5iZiI6MTczNjA0MTg1NSwicGF0aCI6Ii8xODE1NzU2MjgvNDAwMTIzMDMyLWM1NDY1YmQyLTlkZjEtNGNkNS05Mjc3LTY1MWI5MWNiZDg5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQwMTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmMyY2RhNmFkNTUzMTA0YjBmZGUyMzZhMGRkOWZkOTE5NTRmNjkwNTFhYWJiOGIzNDIxOTI2ZTQ0Mzk2ZGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.grgH4OBScMNTjIJ1HgPy7FTFmdmKMVHa8zYGMb8NSwk)

You probably didn't make the correct modifications to the `task.py` file. Please modify the content above according to this issue. Thank you.

**Comment by 15820364259** [comment]
你好，我可以要一下视频文件吗，我想使用视频检测功能，需要关于数据集的视频

**Comment by RDXiaoLu** [comment]
> 你好，我可以要一下视频文件吗，我想使用视频检测功能，需要关于数据集的视频，[2822116198@qq.com](mailto:2822116198@qq.com)，这是我的邮箱，麻烦大佬

Hello,  Here are **5 additional coral videos** captured from the same location. They have already been shared and are ready for download. Wishing you success in your research.⭐
